name: 'Detect build issues & coding standards'

on:
  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📥 dependency installation
        uses: ./.github/actions/pnpm-install

      # Run the linter and verifies the formatting of a set of files. If any errors are found the process exits with a code of 1.
      - name: Validate code standards
        run: pnpm validate:ci

      # Run the build
      - name: Generate dependencies
        run: pnpm sdk generate

      # Run the build
      - name: Build @onbeam/sdk
        run: pnpm sdk prepublish