name: Sonarqube

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: BuildOnBeam/shared-gh-actions/sonarqube@main
        with:
          should-validate-quality: true
          sonar-host-url: ${{ vars.SONAR_HOST_URL }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
