name: Sonarqube

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sonarqube:
    uses: BuildOnBeam/shared-gh-actions/sonarqube/action.yml@main
    secrets: inherit
