name: Sonarqube

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sonarqube:
    uses: Merit-Circle/shared-gh-actions/.github/workflows/sonarqube.yml@main
    secrets: inherit
